-- Add GOOGLE_ANALYTICS provider
ALTER TYPE "Provider" ADD VALUE IF NOT EXISTS 'GOOGLE_ANALYTICS';

-- Add website traffic event types
ALTER TYPE "FunnelEventType" ADD VALUE IF NOT EXISTS 'WEBSITE_VISIT';
ALTER TYPE "FunnelEventType" ADD VALUE IF NOT EXISTS 'PAGE_VIEW';

-- Add GOOGLE_ANALYTICS event source
ALTER TYPE "EventSource" ADD VALUE IF NOT EXISTS 'GOOGLE_ANALYTICS';
